// Downloads Google Fonts woff2 (latin + latin-ext only) and writes a local @font-face
// stylesheet so nothing is loaded from Google at runtime (GDPR-friendly, faster).
import { writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = path.join(ROOT, "assets", "fonts");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36";
const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Archivo+Black&family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&family=IBM+Plex+Mono:wght@400;500;600;700&display=swap";
const KEEP = new Set(["latin", "latin-ext"]);

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();
await mkdir(FONT_DIR, { recursive: true });

// split into blocks, each preceded by /* subset */
const blocks = css.split("/*").slice(1);
let out = "/* Self-hosted fonts — generated by scripts/fetch-fonts.mjs (no external requests) */\n";
let count = 0;
const seen = new Set();

for (const raw of blocks) {
  const subset = raw.slice(0, raw.indexOf("*/")).trim();
  if (!KEEP.has(subset)) continue;
  const block = "@font-face" + raw.split("@font-face")[1];
  if (!block) continue;
  const fam = (block.match(/font-family:\s*'([^']+)'/) || [])[1] || "font";
  const wght = (block.match(/font-weight:\s*(\d+)/) || [])[1] || "400";
  const style = (block.match(/font-style:\s*(\w+)/) || [])[1] || "normal";
  const url = (block.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  const range = (block.match(/unicode-range:\s*([^;}]+)/) || [])[1] || "";
  if (!url) continue;
  const name = `${fam.replace(/\s+/g, "")}-${wght}-${style}-${subset}.woff2`;
  if (!seen.has(name)) {
    const buf = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
    await writeFile(path.join(FONT_DIR, name), buf);
    seen.add(name);
    count++;
    process.stdout.write(`  ✓ ${name} (${(buf.length / 1024).toFixed(0)}KB)\n`);
  }
  out +=
    `@font-face{font-family:'${fam}';font-style:${style};font-weight:${wght};font-display:swap;` +
    `src:url(../fonts/${name}) format('woff2');` +
    (range ? `unicode-range:${range.trim()};` : "") +
    `}\n`;
}

await writeFile(path.join(ROOT, "assets", "css", "fonts.css"), out);
console.log(`\nDone: ${count} font files → assets/fonts/, stylesheet → assets/css/fonts.css`);
